server:
  port:
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
  thymeleaf:
    cache: false

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: tk.mapper.model
logging:
  config: classpath:logback.xml
