server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xgtw_digital?characterEncoding=utf-8
    username: root
    password: root
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: detect
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: tk.mapper.model
logging:
  config: classpath:logback.xml

Props:
  mailProps:
    sendAccount: stlcwjhzx@163.com
    sendPassword: stl666
    SMPHost: smtp.163.com
